dbConfig:
  host: localhost
  port: 27017
  dbName: stockit

server:
  port: 3000
  sessionSecret: fzeoijfiozejfioejzio

authServer:
  url: login.stickit.local
  accessTokenDuration: 60 #60 Mins
  refreshTokenDuration: 72 #72h
  scopes:
    - all